### ISSUE TITLE
A Error in training

### ISSUE THREAD

**Issue by ytddd75** [Elin24/SPDCN-CAC#2]
Thank you for your sharing. May I ask that after data preprocessing according to the code you provided, the training program reported an error: 
File "/home/counting/SPDCN-CAC-main/datasets/dataset.py", line 56, in getSample
    dotmap[0, points[:, 1], points[:, 0]] = 1
IndexError: index 384 is out of bounds for axis 1 with size 384

**Comment by Elin24** [comment]
This happened because the point locations may be out of range. I add the `clip()` function to avoid it, as shown in [line-56](https://github.com/Elin24/SPDCN-CAC/blob/07032e76eaa0286cd0a1d3bde77ec527dc9bfb90/datasets/dataset.py#L56):
```
points[:, 1] = torch.clip(points[:, 1], min=0, max=h-1)
points[:, 0] = torch.clip(points[:, 0], min=0, max=w-1)
```

**Comment by ytddd75** [comment]
Thanks for your thoughtful reply, the problem has been solved. 
By the way, dose the code you provide allow for multi-GPU training?

**Comment by Elin24** [comment]
I'm afraid the answer is no. 

However, the batch size is 16, and the memory requirement is about 21G, so one 3090-GPU is enough to train this model. You can reduce the batch size and adjust the learning rate accordingly for training with limited resources.

Another way to reduce computation costs is using FP16, which may decrease the accuracy a little but save lots of memory.

**Comment by ytddd75** [comment]
Thanks for your thoughtful reply.
