### ISSUE TITLE
How can i use

### ISSUE THREAD

**Issue by ESonicDogan497** [Elin24/SPDCN-CAC#4]
Hello! I have done all the steps, but how can I include the image I want in the code to process it? You didn't write this part.

**Comment by Elin24** [comment]
Hello, I wrote a short demo to show how to inference with your own image: [demo.ipynb](https://github.com/Elin24/SPDCN-CAC/blob/main/demo.ipynb).
You can also update the repo to access the newest update (the demo file).

**Comment by ESonicDogan497** [comment]
Can you write code that doesn't use CUDA?

**Comment by Elin24** [comment]
In the first cell of the [demo.ipynb](https://github.com/Elin24/SPDCN-CAC/blob/main/demo.ipynb), I add a line to select device, You can now use cpu for interence.

**Comment by ESonicDogan497** [comment]
Thank you so much
