### ISSUE TITLE
Program syntax error

### ISSUE THREAD

**Issue by AHdengrui** [Elin24/SPDCN-CAC#6]
Why did I encounter this error while running gendata384x576. py

File "gendata384x576.py", line 80, in <module>
    category = cates[imid]
KeyError: '1050'

**Comment by Elin24** [comment]
There is indeed a line containing the image with id 1050, as shown in [FSC147](https://github.com/cvlab-stonybrook/LearningToCountEverything/blob/00ea1888c3a7c495ae06db0bddc3b90b7db8d52f/data/ImageClasses_FSC147.txt#L772), can you present more details?

**Comment by AHdengrui** [comment]
Thank you for your reply. I have resolved the above issue

**Comment by AHdengrui** [comment]
Thank you for your reply. I have resolved the above issue
